# Path to the directory containing the fine-tuned model, tokenizer, and config.
# This should be the output directory from a training run.
# Example: 'output/models/bert-base-cased/train-50/sample-1'
model_path: 'output/models/bert-base-cased/train-50/sample-1'

# Path to the test data file (.jsonl format).
# You should have a separate test set that the model has not seen.
# Example: 'data/raw/test.jsonl'
test_file: 'data/raw/test.jsonl' 

# Directory where the evaluation results (metrics and predictions) will be saved.
output_dir: 'output/evaluation_results'

# Evaluation batch size.
batch_size: 16