# configs/evaluation_re_config.yaml
# Task type to guide the evaluation script
task: "re"

# Path to the directory containing the fine-tuned RE model.
model_path: 'output/models_re/bert-base-cased/train-50/sample-1'

# Path to the test data file (.jsonl format).
test_file: 'data/processed/test.jsonl'

# A list of the distinct relation types for the RE model.
# This must match the configuration used during training.
relation_labels:
  - "describir"
  - "ubicar"

# Directory where the evaluation results will be saved.
output_dir: 'output/evaluation_results/re'

# Evaluation batch size.
batch_size: 16