# Configuration for the Retrieval-Augmented Generation (RAG) pipeline.
# This file centralizes settings for the LLM provider, vector database,
# and prompting strategies for the NER task.

"task": "ner"

# Test file
test_file: "data/processed/test.jsonl"

# --- LLM Configuration ---
llm:
  # The active provider to be used by the factory.
  # This key determines which client implementation will be loaded.
  # Supported options: "openai", "aws_sagemaker" (future)
  provider: "openai"

  # --- Provider-Specific Configurations ---

  # Settings for the OpenAI client.
  # These are used only when provider is set to "openai".
  # Settings for the OpenAI client.
  # These are used only when provider is set to "openai".
  openai:
    # Specifies the exact model to use from the OpenAI API.
    # This can be changed to any compatible model name.
    # Examples: "gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"
    model: "gpt-4.1-mini-2025-04-14"

    # Controls the randomness of the output. Lower values make the model
    # more deterministic and focused.
    temperature: 0.1

    # --- Start of new lines to add ---
    # Settings for handling API requests, including timeouts and retries.
    request_settings:
      # The maximum number of times to retry a request if it times out.
      max_retries: 3
      # The initial timeout in seconds for the first API call attempt.
      initial_timeout_seconds: 60
      # The multiplier to increase the timeout for each subsequent retry.
      # e.g., 1.5 means the next timeout will be 1.5x the previous one.
      backoff_factor: 1.5

  # Settings for a future AWS SageMaker client.
  # These are used only when provider is set to "aws_sagemaker".
  aws_sagemaker:
    # The name of the deployed SageMaker endpoint that hosts the model.
    endpoint_name: "llama-3-70b-instruct-placeholder"

    # The AWS region where the SageMaker endpoint is deployed.
    region: "us-east-1"


# --- Vector Database Configuration ---
vector_db:
  # Path where the FAISS index file will be stored.
  index_path: "output/vector_db/faiss_index_0.bin"

  # Path to the source data used to build the vector database.
  # This should be the global training set created by generate_partitions.py.
  source_data_path: "data/processed/train-5/sample-1/train.jsonl"

  # The name of the sentence-transformer model to use for generating embeddings.
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"


# --- RAG Prompting Configuration ---
rag_prompt:
  # Path to the text file containing the prompt template.
  prompt_template_path: "prompts/ner_rag_prompt_spanish.txt"
  
  # The number of similar examples to retrieve from the vector database
  # to include in the few-shot prompt.
  n_examples: 0

  # The list of entity labels to be extracted by the LLM.
  # Providing a clear name and description for each label is crucial for
  # guiding the model to make accurate and consistent extractions.
  entity_labels:
    - name: "HALL_presente"
      description: "hallazgos presentes, observaciones de posible importancia patológica. En la gran mayoría de los casos son sólo una palabra, tales como: 'nódulo', 'microcalcificaciones', 'quistes', 'asimetría', etc. En casos particulares, se requiere más de una palabra, como 'clips quirúrgicos' o 'imágenes espiculadas'."
    - name: "HALL_ausente"
      description: "hallazgos ausentes, menciones de hallazgos no presentes, se marca el mismo tipo de palabras que en HALL_presente, pero que hayan sido negadas."
    - name: "CARACT"
      description: "características asociadas a hallazgos presentes o ausentes, tales como: 'isodenso', 'agrupadas', 'bordes bien definidos', etc."
    - name: "CUAD"
      description: "cuadrante de la mama, tales como: 'cuadrante superior interno', 'cuadrante inferoexterno', etc."
    - name: "LAT"
      description: "lateralidad de la mama, puede ser 'derecha', 'izquierda', 'bilateral', 'ambas mamas', etc."
    - name: "REG"
      description: "región de la mama, puede ser 'tercio superior', 'regiones axilares', etc."
    - name: "DENS"
      description: "frases que se refieran a características generales de la densidad mamaria."