# Configuration for a single Relation Extraction (RE) training run.

# Seed for reproducibility
seed: 42

# Training settings
trainer:
  n_epochs: 10
  batch_size: 16 # Batch size can often be larger for RE
  learning_rate: 2e-5
  gradient_accumulation_steps: 1
  warmup_ratio: 0.1
  weight_decay: 0.01
  device: "cuda"  # "cuda" or "cpu"

# Model configuration
model:
  # Hugging Face model identifier for a pre-trained model.
  base_model: "dccuchile/bert-base-spanish-wwm-cased"

  # A list of the distinct relation types in your dataset.
  # The data loader will map these to integer IDs.
  # "No_Relation" is a critical label for pairs of entities with no defined relation.
  relation_labels:
    - "describir"
    - "ubicar"
    - "No_Relation"
    
# Paths and directories
paths:
  # Path to a training data file, relative to the project root.
  # NOTE: This path is IGNORED when using the batch training script,
  # as it dynamically finds the training files in the --partition-dir.
  train_file: 'data/processed/train-50/sample-1/train.jsonl'

  # Directory where the final trained RE model will be saved.
  # Models are saved in a separate directory to distinguish them from NER models.
  output_dir: "output/models"